# Generated by Django 5.2.7 on 2025-11-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
