# Generated by Django 5.2.7 on 2025-11-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='unit',
            name='question_group',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
