# Generated by Django 5.2.7 on 2025-12-02 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_public_id_questioncomment_public_id_and_more'),
        ('courses', '0003_alter_course_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.unitsubtopic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Session',
                'verbose_name_plural': 'Test Sessions',
            },
        ),
    ]
