# Generated by Django 5.2.7 on 2025-11-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_public_id_questioncomment_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='image_file',
            field=models.ImageField(unique=True, upload_to='question_images/'),
        ),
    ]
