# Generated by Django 5.2.7 on 2025-11-22 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_questionanalytics_user_and_more'),
        ('courses', '0003_remove_unitsubtopic_question_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='discrimination',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='question',
            name='guessing',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='question',
            name='selection_frequency',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.unitsubtopic'),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.questioncomment'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='answer_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='questionanalytics',
            name='updated_ability_score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='group_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='selection_frequency',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='savedforlater',
            unique_together={('user', 'question')},
        ),
    ]
