# Generated by Django 5.2.7 on 2026-01-11 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_questionimage_image_file'),
        ('courses', '0004_alter_unit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('current_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.unitsubtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Session',
                'verbose_name_plural': 'Test Sessions',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
