# Generated by Django 5.2.7 on 2026-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='current_question',
        ),
        migrations.AddField(
            model_name='testsession',
            name='excluded_questions',
            field=models.ManyToManyField(blank=True, to='core.question'),
        ),
    ]
