# Generated by Django 5.2.7 on 2025-11-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_discrimination_question_guessing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='answer_explanation',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_explanation',
            field=models.TextField(blank=True),
        ),
    ]
