# Generated by Django 5.2.7 on 2026-01-11 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_testsession_current_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='core.question'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='excluded_questions',
            field=models.ManyToManyField(blank=True, related_name='excluded', to='core.question'),
        ),
    ]
