# Generated by Django 5.2.7 on 2026-01-31 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_testsession_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='current_question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='core.question'),
        ),
    ]
