# Generated by Django 5.2.7 on 2026-01-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testsession_current_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='excluded_questions',
            field=models.ManyToManyField(blank=True, default=list, related_name='excluded', to='core.question'),
        ),
    ]
