# Generated by Django 5.2.7 on 2026-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_testsession_excluded_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='use_out_of_range_questions',
            field=models.BooleanField(default=False),
        ),
    ]
