# Generated by Django 5.2.7 on 2026-03-01 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_testsession_current_question'),
        ('courses', '0005_aidtype_public_id_course_public_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveTestQuestionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('questions_since_last_skipped', models.IntegerField(default=0)),
                ('total_times_skipped', models.IntegerField(default=0)),
                ('total_times_seen', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adaptive Test Question Metrics',
                'verbose_name_plural': 'Adaptive Test Question Metrics',
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='TestingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bayesian_mle_threshold', models.FloatField(default=0.0)),
                ('question_selection_window', models.FloatField(default=0.5)),
                ('skip_readmit_delay', models.IntegerField(default=5)),
                ('max_skips', models.IntegerField(default=3)),
                ('max_question_repetitions', models.IntegerField(default=3)),
                ('min_questions_between_repitions', models.IntegerField(default=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Testing Parameters',
                'verbose_name_plural': 'Testing Parameters',
            },
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
    ]
