# Generated by Django 5.2.7 on 2026-01-30 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_testsession_use_out_of_range_questions'),
        ('courses', '0004_alter_unit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testsession',
            unique_together={('user', 'subtopic')},
        ),
        migrations.AddField(
            model_name='testsession',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, default=list, related_name='answered', to='core.question'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='difficulty_range',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='skipped_questions',
            field=models.ManyToManyField(blank=True, default=list, related_name='skipped', to='core.question'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='current_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='core.question'),
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='course',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='excluded_questions',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='use_out_of_range_questions',
        ),
    ]
