# Generated by Django 5.2.7 on 2026-03-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adaptivetestquestionmetrics_testingparameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingparameters',
            name='bayesian_mle_threshold',
        ),
        migrations.AddField(
            model_name='testingparameters',
            name='warmpup_length',
            field=models.IntegerField(default=3),
        ),
    ]
