# Generated by Django 5.2.7 on 2026-03-09 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_testingparameters_bayesian_mle_threshold_and_more'),
        ('courses', '0005_aidtype_public_id_course_public_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingparameters',
            name='question_selection_window',
        ),
        migrations.AddField(
            model_name='testingparameters',
            name='suggested_stopping_threshold',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='testingparameters',
            name='window_increment',
            field=models.FloatField(default=0.25),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('selection_upper_bound', models.FloatField(default=0.5)),
                ('selection_lower_bound', models.FloatField(default=0.5)),
                ('has_seen_stop_message', models.BooleanField(default=False)),
                ('subtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.unitsubtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Session',
                'verbose_name_plural': 'Test Sessions',
            },
        ),
    ]
