# Generated by Django 5.2.7 on 2026-03-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_testingparameters_question_selection_window_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptivetestquestionmetrics',
            name='questions_since_last_skipped',
        ),
        migrations.AddField(
            model_name='adaptivetestquestionmetrics',
            name='skipped_at_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='questions_answered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='selection_lower_bound',
            field=models.FloatField(default=-0.5),
        ),
    ]
