# Generated by Django 5.2.7 on 2026-03-12 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_adaptivetestquestionmetrics_questions_since_last_skipped_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdaptiveTestQuestionMetrics',
            new_name='AdaptiveTestQuestionMetric',
        ),
        migrations.AlterModelOptions(
            name='adaptivetestquestionmetric',
            options={'verbose_name': 'Adaptive Test Question Metric', 'verbose_name_plural': 'Adaptive Test Question Metrics'},
        ),
        migrations.RenameField(
            model_name='adaptivetestquestionmetric',
            old_name='total_times_skipped',
            new_name='skips_since_last_answer',
        ),
    ]
