# Generated by Django 5.2.7 on 2026-04-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_courseresumestate_and_adaptive_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
