# Generated by Django 5.2.7 on 2026-04-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_question_public_id_and_more'),
        ('core', '0014_questionoption_explanation'),
    ]

    operations = [
    ]
