# Generated by Django 6.0.4 on 2026-04-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_adaptivetestquestionmetric_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptivetestquestionmetric',
            name='last_seen_at_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
