# Generated by Django 5.2.7 on 2025-11-23 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answered_correctly', models.BooleanField()),
                ('updated_ability_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('time_spent', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Attempt',
                'verbose_name_plural': 'Question Attempts',
            },
        ),
        migrations.CreateModel(
            name='UserTopicAbilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('unit_sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.unitsubtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Topic Ability Score',
                'verbose_name_plural': 'User Topic Ability Scores',
                'unique_together': {('user', 'unit_sub_topic')},
            },
        ),
    ]
