# Generated by Django 5.2.7 on 2025-11-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopicabilityscore',
            name='variance',
            field=models.DecimalField(decimal_places=4, default=10.0, max_digits=6),
        ),
    ]
