# Generated by Django 5.2.7 on 2026-03-10 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usertopicabilityscore_variance'),
        ('core', '0007_alter_testsession_current_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reason', models.CharField(choices=[('Formatting of text', 'Text Formatting'), ('Formatting of images', 'Image Formatting'), ('Images were incorrect', 'Incorrect Images'), ('Solution incorrect or confusing', 'Solution Incorrect'), ('Question incorrect or confusing', 'Question Incorrect'), ('Other', 'Other')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Report',
                'verbose_name_plural': 'Question Reports',
            },
        ),
    ]
