# Generated by Django 5.2.7 on 2026-03-01 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usertopicabilityscore_variance'),
        ('core', '0007_alter_testsession_current_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('user', 'question', 'timestamp')},
        ),
    ]
