# Generated by Django 5.2.7 on 2026-03-22 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usertopicabilityscore_variance'),
        ('core', '0012_rename_adaptivetestquestionmetrics_adaptivetestquestionmetric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('user', 'question', 'timestamp')},
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Report',
                'verbose_name_plural': 'Question Reports',
            },
        ),
        migrations.CreateModel(
            name='QuestionReportReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Formatting of text', 'Text Formatting'), ('Formatting of images', 'Image Formatting'), ('Images are incorrect', 'Incorrect Images'), ('Solution incorrect or confusing', 'Solution Incorrect'), ('Question incorrect or confusing', 'Question Incorrect'), ('Other', 'Other')], max_length=100)),
                ('question_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_reasons', to='analytics.questionreport')),
            ],
            options={
                'verbose_name': 'Question Report Reason',
                'verbose_name_plural': 'Question Report Reasons',
                'unique_together': {('question_report', 'reason')},
            },
        ),
    ]
