# Generated by Django 5.2.7 on 2026-03-13 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_questionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionreport',
            name='reason',
        ),
        migrations.AddField(
            model_name='questionreport',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuestionReportReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Formatting of text', 'Text Formatting'), ('Formatting of images', 'Image Formatting'), ('Images are incorrect', 'Incorrect Images'), ('Solution incorrect or confusing', 'Solution Incorrect'), ('Question incorrect or confusing', 'Question Incorrect'), ('Other', 'Other')], max_length=100)),
                ('question_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_reasons', to='analytics.questionreport')),
            ],
            options={
                'verbose_name': 'Question Report Reason',
                'verbose_name_plural': 'Question Report Reasons',
            },
        ),
    ]
