# Generated by Django 5.2.7 on 2026-04-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_coursexp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursexp",
            options={"verbose_name": "Course XP", "verbose_name_plural": "Course XP"},
        ),
    ]
