# Generated by Django 5.2.7 on 2026-03-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_questionreport_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionreport',
            name='contact_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='questionreportreason',
            unique_together={('question_report', 'reason')},
        ),
    ]
