# Generated by Django 5.2.7 on 2026-03-30 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_coursexp'),
        ('core', '0013_merge_courseresumestate_and_adaptive_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursexp',
            options={'verbose_name': 'Course XP', 'verbose_name_plural': 'Course XP'},
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.question'),
        ),
    ]
