# Generated by Django 5.2.7 on 2026-03-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_questionreport_contact_consent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionreport',
            name='contact_consent',
        ),
    ]
