# Generated by Django 5.2.7 on 2026-04-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_coursexp_options'),
        ('analytics', '0005_alter_coursexp_options_alter_questionreport_question'),
    ]

    operations = [
    ]
