# Generated by Django 5.2.7 on 2025-11-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('FALL', 'Fall'), ('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('MULTI_TERM', 'Multi-term')], max_length=20),
        ),
    ]
