# Generated by Django 5.2.7 on 2025-11-22 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_unit_question_group_unitsubtopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitsubtopic',
            name='question_group',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_ta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unitsubtopic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unitsubtopic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userscorefortopic',
            name='score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='StudyAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reference', models.TextField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.unitsubtopic')),
            ],
        ),
    ]
