# Generated by Django 5.2.7 on 2025-12-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['number'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
