# Generated by Django 5.2.7 on 2026-03-10 06:22

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_aidtype_public_id_course_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='unitsubtopic',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
