# Generated by Django 5.2.7 on 2026-03-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_aidtype_public_id_course_public_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('course', 'number')},
        ),
    ]
