# Generated by Django 5.2.7 on 2026-04-01 03:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_aidtype_public_id_course_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionUploadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('RUNNING', 'Running'), ('FAILURE', 'Failure')], max_length=20)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Question Upload Result',
                'verbose_name_plural': 'Question Upload Results',
            },
        ),
        migrations.CreateModel(
            name='QuestionUploadFailures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('question_identifier', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('upload_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='courses.questionuploadresult')),
            ],
            options={
                'verbose_name': 'Question Upload Failure',
                'verbose_name_plural': 'Question Upload Failures',
            },
        ),
    ]
