# Generated by Django 5.2.7 on 2026-04-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_tag_to_unit_and_unitsubtopic'),
        ('courses', '0006_alter_aidtype_public_id_alter_course_public_id_and_more'),
        ('courses', '0007_questionuploadresult_initiating_user'),
    ]

    operations = [
    ]
