# Generated by Django 5.2.7 on 2026-04-07 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20260407_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionuploadfailures',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionuploadresult',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
