# Generated by Django 5.2.7 on 2025-11-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macfastuser',
            name='ability_score',
        ),
    ]
