# Generated by Django 5.2.7 on 2026-01-31 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_aidtype_public_id_course_public_id_and_more'),
        ('sso_auth', '0002_remove_macfastuser_ability_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='macfastuser',
            name='active_subtopic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='courses.unitsubtopic'),
        ),
    ]
