# Generated by Django 5.2.7 on 2026-01-30 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_unit_options'),
        ('sso_auth', '0002_remove_macfastuser_ability_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='macfastuser',
            name='active_subtopic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='courses.unitsubtopic'),
        ),
    ]
